version: "3.9"

services:
    yonker-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: yonkers
        command: /start_app
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"

    yonker-worker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: yonker_worker
        command: /start_celery
        env_file:
            - .env
        volumes:
            - .:/usr/src/app

    flower:
        build:
            context: .
            dockerfile: Dockerfile
        image: yonker_flower
        container_name: yonker_flower
        env_file:
            - .env
        command: /flower_start
        volumes:
            - .:/usr/src/app
        ports:
            - 5557:5555

networks: 
    default:
        external: true
        name: service-network